language: ruby
rvm:
- 2.2
bundler_args: ''
branches:
  only:
  - dev
before_install:
- git config --global user.name "Travis CI"
- git config --global user.email ${EMAIL}
script:
- bundle exec jekyll build
after_success:
- git clone https://$GITHUB_REPO
- cd $(basename ${GITHUB_REPO%.git})
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/xhuang68/portfolio.git
  - REPO_TARGET_BRANCH: gh-pages
  - GH_REF: github.com/xhuang68/portfolio.git
