language: ruby
rvm:
- 2.2
bundler_args: ''
branches:
  only:
  - dev
before_install:
- git config --global user.name "Travis CI"
- git config --global user.email ${EMAIL}
script:
- bundle exec jekyll build
after_success:
- git clone https://$GITHUB_REPO
- cd $(basename ${GITHUB_REPO%.git})
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/xhuang68/portfolio.git
  - REPO_TARGET_BRANCH: gh-pages
  - GH_REF: github.com/xhuang68/portfolio.git
  - secure: O+9XQid8DpYEuWFtdavxT3NXf4Os1mXNre5S6yhGOq0bdKAsvtrTEj5b5sQVqqBk6+AMS6tphEI3w31AFuzMt829RD/jP4qh4KDt0nIakpnHnmONrG4d1GQu8kU/JPxYApD02urreUJ9Yx8Z5g15vMlucCeTZ1XtWNwPvwGLoy29VQ7odnWMtEoH12o00FHRD06CuBLfMGdyZrtB37qDkQ1vcItUN70U70uKEAPsufYRfMwOMgk2TWVKtqGRaOv9TRmGtKVQNrbDtosoPHQ5Kvd/VrhUHX27bh+pM79wPhD5mECWfyhsVo/zTncqWgO3kMJp4MoSG14ZyJ/2bK9KfrVSQO7h8inCSMsWZI5UwgnDR7BAXpCCi0HaJZcit30WW9IaLMsqUpiO72NvzHqUdFB4o4MGevGrlS+/We21vchLtjczrRS3YoPVLFTQ0M7YSt+jM5CjC5meNq/Buwt9rRsIndjeuEa+FqYA1DJRQ9Rme1epWFi0ipBv7MZ9PJp5ssswaiwwHvbkfjjl1FhQXW00l5+Dhu8ZRdx+o+Xb/GC5sNOWy/gnr1NLcjeIgwZKiCRr8FapmBj9uoGzFHw014vrgrU38psQmarA94fh5cdAZKwZWMQbDmcJSSDgQ/5BvIejxoYF3LSxeG16A3tLKHTnn/MHXuwTkrGuJFK0I5w=
  - secure: oc03TJ6nht7X2/h4OTtq0rAzr2OXdtvgFF/75S0/yMdA2puW1RaVcOSc+Is9HNa08v0Mochhzf8jHQgl8ST1k6rNdYxi6sW/4N5dguOHQvQUvxZA+zhi6lbbFsi1CnJ+Fz2DtvUMK9zYvQu924nU6i2oq+GY6Be78KpSZ3L9tQvgpb/QKSl2l5hX4sREC0b8WaMqyUbxaiJy/Gbkxny2BEztOz0EtZPVlvWKlrrFndcy+h7+vFdeq2cWkHg4ZreSD0R7E1CA/a8ztrI58X21GbvtgVhEmFXdM2bP+7g839o5GiLTiH6pjGRTr5L0cNwBsaozZoom0wAn7R2kYK9IA7B2KkgP3GPnPIRR0EzQEaVCMxNBuPdYKkcqsbK5QfHzEEMzKpCa9QrR0uqjb4FH/ufjeFJxy+9M4S7hE7GmDGVyammgzf8146gnbVN2hWFshvATqQKiewB80lProo/ZNZntw1g6W17jnnAPPJcqrfdDBwSXc8OgR4T78ERsyxNb3oLYVgURZMggF8fsdwGTYIZfPGq3zJDENv4+d0upyUZPD6DGtwGSePdXlCk0Owsor/m5Wb7MTfYCL4yLdP3ThQbpVvqNHSYWcraE1qwG4RGCBh6/1+7OIQ6gmIFwijtR7qps1BECemKXn+jiuKuf7CZnyaAIfrGHhgRIE/iUgRA=
