# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://xiaohuang.me
title: Xiao
email: henryhuang1989@gmail.com
author: Xiao Huang
description: > # "This is my portfolio website. Xiao Huang."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: GitHub
    icon: github
    url: https://github.com/xhuang68

  - title: weibo
    icon: weibo
    url: http://weibo.com/henryhuang1989

  - title: twitter
    icon: twitter
    url: https://twitter.com/iHenryhuang
